[package]
name = "sakko"
description = "Sakko programming language: lexer, parser, and AST"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde = { version = "1", default-features = false, features = ["alloc", "derive"] }
chumsky = { version = "1.0.0-alpha.8", features = ["pratt"] }

[dev-dependencies]
serde_json = "1"
