name: Deploy GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Build everything
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'

      # Build Docs site
      - name: Install Docs deps and build docs
        run: |
          cd Docs
          npm ci
          npm run build

      # Prepare full page deploy directory
      - name: Prepare Pages assets
        run: |
          mkdir -p gh-pages-root
          # Docs (site) go to root
          cp -r Docs/site/* gh-pages-root/

      - name: Deploy all assets to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: gh-pages-root
          keep_files: false # Or true, depending
          commit_message: Deploy Docs